---
- hosts: all
  become: yes
  tasks:
  - name: Install Apache on Centos Server
    yum: name=httpd state=latest
   
  - name: Start Apache on Centos Server
    service: name=httpd state=started

  - name: Copy index file
    template:
      src: /etc/ansible/index.html
      dest: /var/www/html/index.html
